### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by rkorebrits** [talendo/protoc-gen-ts-interfaces#1]
When I run 

	protoc --plugin=protoc-gen-ts=${GOPATH}/web/node_modules/protoc-gen-ts-interfaces/bin/protoc-gen-ts-interfaces \
	       --ts_out=${GOPATH}/web/upgrade/projects/common/src/lib/models/sharedproto \
	       --proto_path=${GOPATH}/sharedproto \
	           ${GOPATH}/sharedproto/wallet/*.proto

I get the following error:

	protoc-gen-ts-interfaces error: TypeError: /Users/rkorebrits/workspace/core/web/node_modules/protoc-gen-ts-interfaces/dist/templates/module.ejs:12
	    10| <% } -%>
	    11| <% if(obj.messageTypeList.length > 0) { -%>
	 >> 12| <%- include('messages') -%>
	    13| <% } -%>
	    14| 

	/Users/rkorebrits/workspace/core/web/node_modules/protoc-gen-ts-interfaces/dist/templates/messages.ejs:7
	    5|   <%= field.name -%>?: <%= helpers.fieldType(field, obj.name) %> | null
	    6| <%_ } else if (helpers.isSimpleType(field)) {-%>
	 >> 7|   <%= field.name -%>: <%= helpers.fieldType(field, obj.name) %>
	    8| <%_ } else {-%>
	    9|   <%= field.name -%>?: <%= helpers.fieldType(field, obj.name) %>
	    10| <%_ } -%>

	Cannot read property 'moduleName' of undefined
	    at /Users/rkorebrits/workspace/core/web/node_modules/protoc-gen-ts-interfaces/dist/index.js:70:13
	    at Object.fieldType (/Users/rkorebrits/workspace/core/web/node_modules/protoc-gen-ts-interfaces/dist/index.js:84:46)
	    at message.fieldList.forEach (eval at compile (/Users/rkorebrits/workspace/core/web/node_modules/ejs/lib/ejs.js:618:12), <anonymous>:30:34)
	    at Array.forEach (<anonymous>)
	    at obj.messageTypeList.forEach (eval at compile (/Users/rkorebrits/workspace/core/web/node_modules/ejs/lib/ejs.js:618:12), <anonymous>:15:26)
	    at Array.forEach (<anonymous>)
	    at eval (eval at compile (/Users/rkorebrits/workspace/core/web/node_modules/ejs/lib/ejs.js:618:12), <anonymous>:9:28)
	    at returnedFn (/Users/rkorebrits/workspace/core/web/node_modules/ejs/lib/ejs.js:653:17)
	    at include (/Users/rkorebrits/workspace/core/web/node_modules/ejs/lib/ejs.js:651:39)
	    at eval (eval at compile (/Users/rkorebrits/workspace/core/web/node_modules/ejs/lib/ejs.js:618:12), <anonymous>:31:17)

**Comment by castarco** [comment]
This repository should be archived. If you are still interested in using JOIN's gRPC tools, check these two:

- https://github.com/join-com/grpc
- https://github.com/join-com/protoc-gen-ts
